/**
 * @file actionTypes
 * @author chenbo09
 */

// layout
export const UPDATE_LAYOUT = 'UPDATE_LAYOUT';
export const GET_DEMO_LIST = 'GET_DEMO_LIST';

// upload
export const UPLOAD_CDN = 'UPLOAD_CDN';

// user
export const USER_ALL_LIST = 'USER_ALL_LIST';
export const USER_DETAIL = 'USER_DETAIL';
export const AGENCY_ALL_LIST = 'AGENCY_ALL_LIST';
export const MESSAGE_ALL_LIST = 'MESSAGE_ALL_LIST';
export const SYSTEM_CONF = 'SYSTEM_CONF';
export const ACCOUNT_BASICINFO = 'ACCOUNT_BASICINFO';
export const INDEX_ACCOUNT_BASICINFO = 'INDEX_ACCOUNT_BASICINFO';
export const SYSTEM_CONSTANTS = 'SYSTEM_CONSTANTS';
export const USER_AGENCY_LIST = 'USER_AGENCY_LIST';
export const USER_TRADE = 'USER_TRADE';
export const SINGLE_USER_BALANCE = 'SINGLE_USER_BALANCE';
export const USER_DAILY_LIST = 'USER_DAILY_LIST';
export const USER_DETAIL_STATICS = 'USER_DETAIL_STATICS';
export const USER_BALANCE = 'USER_BALANCE';
export const AGENCY_BALANCE = 'AGENCY_BALANCE';
export const AGENCY_DETAIL = 'AGENCY_DETAIL';
export const MESSAGE_DETAIL = 'MESSAGE_DETAIL';
export const ACCOUNT_ALL = 'ACCOUNT_ALL';
export const CURRENT_USER_BALANCE = 'CURRENT_USER_BALANCE';


// plan
export const PLAN_LIST_GET = 'PLAN_LIST_GET';
export const PLAN_ALL_GET = 'PLAN_ALL_GET';
export const PLAN_DETAIL_GET = 'PLAN_DETAIL_GET';
// unit
export const UNIT_LIST_GET = 'UNIT_LIST_GET';
export const UNIT_ALL_GET = 'UNIT_ALL_GET';
export const UNIT_DEATIL_GET = 'UNIT_ALL_GET';
// idea IDEA_LIST_GET
export const IDEA_LIST_GET = 'IDEA_LIST_GET';
export const IDEA_ALL_PLAN = 'IDEA_ALL_PLAN';
export const IDEA_ALL_UNIT = 'IDEA_ALL_UNIT';
export const IDEA_DETAIL = 'IDEA_DETAIL';
export const AUDIT_LOG = 'AUDIT_LOG';
export const AUDIT_STATISTICS = 'AUDIT_STATISTICS';
export const IDEA_ELEMENT = 'IDEA_ELEMENT';
export const IDEA_ELEMENTALL = 'IDEA_ELEMENTALL';
export const IDEA_ELEMENTALL_DETAIL = 'IDEA_ELEMENTALL_DETAIL';

// keyword
export const KEYWORD_LIST_GET = 'KEYWORD_LIST_GET';
export const KEYWORD_DETAIL_GET = 'KEYWORD_DETAIL_GET';
export const KEYWORD_UNIT_ALL = 'KEYWORD_UNIT_ALL';
export const KEYWORD_PLAN_ALL = 'KEYWORD_PLAN_ALL';

// index
export const GET_IDEA_STATIS = 'GET_IDEA_STATIS';
export const GET_CHART_DAILY = 'GET_CHART_DAILY';
export const GET_BILL = 'GET_BILL';
export const GET_AUDIT = 'GET_AUDIT';
export const GET_INDEX_CHART = 'GET_INDEX_CHART';
export const GET_TOP_SITE = 'GET_TOP_SITE';
export const GET_TOP_IDEA = 'GET_TOP_IDEA';
export const GET_TOP_PROV = 'GET_TOP_PROV';
export const GET_MESSAGE = 'GET_MESSAGE';

// summary
export const GET_CURRENT_USER_BALANCE = 'GET_CURRENT_USER_BALANCE';
export const GET_BILL_STATISTICS = 'GET_BILL_STATISTICS';
export const GET_BILL_LINE_CHART = 'GET_BILL_LINE_CHART';
export const GET_BILL_PIE_CHART = 'GET_BILL_PIE_CHART';
export const GET_BILL_SUMMARY_LIST = 'GET_BILL_SUMMARY_LIST';

// report
export const REPORT_DAILY = 'REPORT_DAILY';
export const REPORT_METRIC = 'REPORT_METRIC';
export const DIRECT_DETAIL = 'DIRECT_DETAIL';
export const REGION_CONF = 'REGION_CONF';
export const ADX_LIST = 'ADX_LIST';
export const BUSINESS_CENTER = 'BUSINESS_CENTER';
export const JRTT_HOBBIES = 'JRTT_HOBBIES';
export const REPORT_DOWNLOAD = 'REPORT_DOWNLOAD';
export const REPORT_ALLPLAN = 'REPORT_ALLPLAN';
export const REPORT_ALLIDEA = 'REPORT_ALLIDEA';
export const REPORT_ALLUNIT = 'REPORT_ALLUNIT';
export const REPORT_ALLDAILY = 'REPORT_ALLDAILY';
export const REPORT_REGIONCONF = 'REPORT_REGIONCONF';
export const TEMPLATE_LIST = 'TEMPLATE_LIST';
export const TEMPLATE_ALL = 'TEMPLATE_ALL';
export const TASK_CHECK = 'TASK_CHECK';
export const TASK_QUERY = 'TASK_QUERY';
export const REPORT_CREATE = 'REPORT_CREATE';
export const TEMPLATE_DTTAIL = 'TEMPLATE_DTTAIL';
export const REPORT_ACTION = 'REPORT_ACTION';
export const REPORT_METRIC_ACTION = 'REPORT_METRIC_ACTION';
export const REPORT_METRIC_CHART = 'REPORT_METRIC_CHART';


// 自定义定向
export const TARGET_ALL = 'TARGET_ALL';
